theme = "custom"

[editor]
line-number = "relative"
whitespace.render = "all"
soft-wrap.enable = true

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"

B = ":sh git log -n 5 --format='format:%%h %%an (%%ar) \"%%s\"' --no-patch -L %{cursor_line},+1:%{buffer_name}"


